mozilla/webdriver-rust

Cargo.toml

this allows us to not have openssl built on windows since it requires gcc in mingw which is a silly dependency. We can look at fixing it at another date.

Set hyper to not build with default-features

---

src/httpapi.rs

This updates all `_` in URLs to be `/` in endpoints as has been done
in the WebDriver Specification.

Update the HTTP Endpoints to match the current specification

---

src/command.rs

The following warnings appear:
```
src/command.rs:344:5: 344:56 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
src/command.rs:344     fn from_json(body: &Json) -> WebDriverResult<Self>;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/command.rs:344:5: 344:56 help: run `rustc --explain E0277` to see a detailed explanation
src/command.rs:344:5: 344:56 note: `Self` does not have a constant size known at compile-time
src/command.rs:344     fn from_json(body: &Json) -> WebDriverResult<Self>;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/command.rs:344:5: 344:56 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
src/command.rs:344     fn …
```

Fix nightly warnings related to lifetimes

---

src/command.rs
src/httpapi.rs
src/lib.rs
src/server.rs

This adds support for extension commands by adding an Extension(T:WebDriverExtensionRoute)
entry to the httpapi::Route enum and Extension(T:WebDriverExtensionCommand) to
command::WebDriverCommand. Users must pass a list of all the extension routes they want
to use when calling server::start. They will also need to ensure that their WebDriverHandler
implementation has the extesnion route type as a type argument

Implement support for extension commands.

---

src/command.rs

The specification was divergent here to WebDriver for no real gain
and this brings it back in line.

Update parameter being used in alert sendKeys

---

.gitignore
src/common.rs
src/lib.rs

Implement `Into<Option<T>>` and `map` for `Nullable` and change `Date`s contained data visibility to public. I also added some rules to `.gitignore` for the sanity of vim users :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/25)

Add extensions `Nullable` and change `Date`s data visibility to pub

---

src/command.rs
src/response.rs

Modify the parsing and storage of AddCookieParameters expiry field to accept a given date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/29)

AddCookieParameters expiry should accept a date

---

Cargo.toml
src/lib.rs
src/response.rs

This is largely for servo/servo#10826.
Implement `Into<cookie::Cookie>` (where cookie is [cookie-rs](https://github.com/alexcrichton/cookie-rs)). Then impl `Serialize` and `Deserialize` in `cookie-rs`.
Either way, we need one common way of representing a cookie... As long as it isn't oatmeal raisin :smile:
CC @asajeffrey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/33)

Implement Into<cookie::Cookie> for Cookie

---

src/server.rs

This should be throwing a Session Not Created Error as described in
http://w3c.github.io/webdriver/webdriver-spec.html#new-session step 2
This fixes https://github.com/mozilla/geckodriver/issues/174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/40)

Correct Error message when starting a second session. 

---

src/command.rs

Instead of Send Alert Text using 'text' it now uses 'value' allowing
us to simplify the parameter checking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/39)

Align Send Alert Text To use same properties as Element Send Keys

---

src/command.rs
src/httpapi.rs

Close Window is the official name of the command for closing windows.
I believe it used to be called just Close some iterations ago.

Rename Close to CloseWindow

---

src/command.rs
src/httpapi.rs

This adds the ability to get Screenshots of just an element as described in
https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot

Add TakeElementScreenshot

---

src/server.rs

The command still throws an error if no connection is still established (`{"error":"unknown error","message":"Got a command with no session?!"}`)
I am not sure if this is what completes the work on the `webdriver-rust` side. With [this implemented in geckodriver](https://github.com/mozilla/geckodriver/compare/master...vkatsikaros:286/status_endpoint) I still get a `{"error":"unknown command","message":"status"}`
References #45

Allow command Status without session id

---

src/response.rs

Fixes https://github.com/mozilla/geckodriver/issues/404.

Allow window position response to hold negative values

---

src/command.rs
src/httpapi.rs

The command for getting a single cookie by name is named ‘Get Named
Cookie’ in the WebDriver specification.  We should reflect this name
in the Rust library.

Rename GetCookie to GetNamedCookie

---

src/server.rs

> ## 5.3 Processing Model
>
> [...]
>
> When required to send a response, with arguments status and data, a
> remote end must run the following steps:
>
> [...]
> 3. Set the response's header with name and value with the following
>    values:
>
>    "Content-Type"
>        "application/json; charset=utf-8"
>    "cache-control"
>        "no-cache"
Source: https://w3c.github.io/webdriver/webdriver-spec.html#dfn-send-a-response
Please note: I have not yet been able to test this patch locally.

Correct response headers

---

src/error.rs
src/response.rs
src/server.rs

This implements [step 4 of the Close Window steps](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-close-window) that [closes the session](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-close-the-session).
When the window handle array sent back from the `CloseWindow` command is empty, delete the session.
It also changes the `WebDriverError`’s API slightly by publishing the `delete_session` field instead of using the hard-to-understand `set_delete_session` and `delete_session` getter/setters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/64)

Delete session on last window

---

Cargo.toml
src/error.rs
src/lib.rs

The WebDriver standard says the stacktrace field on error responses are
implementation-defined, but the field cannot be omitted.  The errors
originating from Marionette are passed on without modification and
include the expected stacktrace.
This exposes a backtrace from the Rust crate with the same name for the
errors originating from within the library itself.
Fixes: https://github.com/mozilla/webdriver-rust/issues/63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/65)

Include backtrace for errors originating from Rust

---

src/command.rs
src/response.rs

WebDriver's timeouts configuration object format changed recently,
and this aligns us with the specification.  Fields in the JSON Object
passed to Set Timeouts as parameters are optional, meaning it is possible
to send `{"search": <u64>}` without defining "pageLoad" or "implicit".
Upon responding, the JSON Object in the body must contain all fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/72)

Align timeouts format with spec

---

src/response.rs

The approach here is a little hacky but it allows us to continue using
rustc_serialize to encode the data and avoids changing the internal API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/73)

Wrap responses in a 'value' key.

---

src/command.rs

Fixes: https://github.com/mozilla/webdriver-rust/issues/77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/78)

Match on correct implicit timeout duration key

---

src/command.rs

Okay, who's the lucky reviewer who wants to help me learn Rust? @jgraham r?
Good: This compiles.
Bad: I haven't been able to test it because I can't compile geckodriver after updating the webdriver dependency to point to my local changes. I think maybe the two are out of sync in many ways. 
Anyway, I appreciate the opportunity to write some Rust, and I realize this PR may still need a lot of work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/76)

Replace element with origin in PointerMove

---

src/command.rs

In Bug 1347658, negative numbers were allowed for pointer move.
This was added to the WebDriver specification in December.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/81)

Allow negative numbers for x and y on pointerMove.

---

src/capabilities.rs

Should fix https://github.com/mozilla/geckodriver/issues/631.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/87)

Fix validate_port if value is a Json::U64.

---

src/server.rs

The characters "←" and "→" are obfuscated in the Windows command
prompt.  Use ASCII versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/96)

Make log output safe for windows prompt

---

src/capabilities.rs

The W3C spec requires the American spelling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/97)

Fix spelling of unhandledPromptBehavior.

---

src/server.rs

Fixes #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/99)

Don't return existing session id when the wrong one is supplied

---

src/response.rs

This merges the WindowRectResponse and ElementRectResponse into
a single struct. It also moves the types in the struct to floats which
aligns with the WebDriver specification as in
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect
and in https://w3c.github.io/webdriver/webdriver-spec.html#dfn-window-rect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/101)

Simplify Responses for Rect type calls to use same `struct` and `impl`

---

src/response.rs

The WebDriver specification mandates that the GetNamedCookie command
should return a cookie serialisation object, and not an array of
cookies.
This patch introduces WebDriverResponse::Cookie and CookieResponse types
to allow WebDriver implementations to return single cookie objects.
Fixes: https://github.com/mozilla/geckodriver/issues/463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/102)

response: add single cookie response type

---

src/command.rs
src/httpapi.rs

Symptom: Now webdriver-rust cannot minimize window
Root Cause: No minimize command
Solution: Add the minimize command
Project: webdriver-rust
Note: After add this patch
Then add one in geckodriver
Then add support in firefox(marionette)
At last add patch in selenium(firefox webdriver)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/105)

Implement the minimize window for webdriver-rust

---

src/common.rs
src/response.rs

The WebDriver specification recently introduced an additional "state"
field for the window rect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/109)

common, response: add window state to window rect response

---

src/command.rs
src/common.rs
src/error.rs
src/httpapi.rs
src/response.rs
src/server.rs

This PR will fix issue #110.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/111)

Use derive debug for custom enum and struct definitions

---

src/capabilities.rs

This PR implements the correct handling of the proxy ports which are now part of the proxy host capability. By doing that a lot of not needed code can be removed, which also makes our handling more stable.
This change provides basic unit tests but I will add more detailed wdspec tests later when the refactoring is getting done.
Closes #115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/116)

Make proxy port an optional suffix for each *Proxy capability

---

src/common.rs

While creating WDSpec for Find Element and similar commands it showed
that we do not support Tag Name as a valid selector. Tests can be found
at https://reviewboard.mozilla.org/r/172110/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/118)

Add Tag Name as a valid location strategy.
