mozilla/webdriver-rust

Cargo.toml
CC https://github.com/servo/servo/pull/8446
=> Update to hyper 0.7

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/24)
=> Bump hyper to 0.8

Cargo.toml, src/command.rs, src/common.rs, src/error.rs, src/httpapi.rs, src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/26)
=> Various cleanup.

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/27)
=> Add travis CI support.

src/command.rs, src/error.rs, src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/30)
=> Add support for capabilites in New Session command

src/marionette_bits.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/32)
=> marionette_bits: remove

src/command.rs
@asajeffrey mind being a reviewer for this repo? And with that in mind, r? for this change in particular :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/34)
=> Implement to_json for NewSessionParameters

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/35)
=> disable default feature cookie/secure as to not depend on openssl

src/command.rs, src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/38)
=> Add ability to consume capabilities.

src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/41)
=> Return hyper::server::Listening so user can access socket address

src/server.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgraham/webdriver-rust/43)
=> Return early using try!() instead of unwrapping errors

src/server.rs
=> Allow calling status command without a session being started.

README.md
Provides info I was looking for when this came up on Google.
=> Help googlers

src/command.rs
Previously this used String.len() which was incorrect since it counts bytes, not characters.
Moving to a chars() iterator fixes the issue.
=> Fix check that key codes in actions are a single char.

src/command.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/69)
=> Fix pointerMove and pointerCancel action types

Cargo.toml, src/response.rs
happy to hear suggestions about improving the into function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/70)
=> bumped hyper to 0.10 and cookie to 0.6, bumped version to 0.19.1

src/error.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/74)
=> Wrap error responses in a 'value' object.

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/75)
=> Update version number for release

src/response.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/79)
=> Fix CookieResponse and CloseWindowResponse serialization.

src/command.rs
Expect a property called "text" that takes a string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/80)
=> Update SendKeysParameters to match spec.

src/httpapi.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/82)
=> Remove end points no longer supported by Selenium.

src/command.rs, src/httpapi.rs, src/response.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/83)
=> Add window rect commands

src/capabilities.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/88)
=> Recognize sslProxy and sslProxyPort capabilities.

src/capabilities.rs, src/command.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/89)
=> Provide a few structs with Debug trait

src/capabilities.rs
According to https://tools.ietf.org/html/rfc2732 and
https://url.spec.whatwg.org/, IPv6 hostnames when represented in URLs
must be enclosed with "[" and "]" bracket characters.
Fixes: https://github.com/mozilla/geckodriver/issues/655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/92)
=> Enclose IPv6 hosts in brackets before testing URL

src/command.rs, src/error.rs, src/server.rs
The changes are explained in the individual commit messages, but should seen in light of https://github.com/mozilla/geckodriver/pull/636. Put together, these two PRs significantly reduces and improves the logging output produced by geckodriver. This should help a lot when diagnosing bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/90)
=> Reduce and improve HTTP request logging

src/command.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/95)
=> Fix error messages for timeout params.

Cargo.toml
Fixes #103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/104)
=> Bump cookie dependency to 0.9

src/capabilities.rs
This is the fix for issue #106.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/107)
=> Use proxyType "direct" instead of "noproxy"

src/capabilities.rs
This fixes issue #113.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/webdriver-rust/114)
=> Fix invalid check for scheme in proxy host.
